vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

# mappings : chemin / on peut renommer pour avoir livres/auteurs à la place de products (pour les images de couverture et les photos d'auteurs)
    mappings:
       livres:
           uri_prefix: /images/livres
           upload_destination: '%kernel.project_dir%/public/images/livres'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       auteurs:
           uri_prefix: /images/auteurs
           upload_destination: '%kernel.project_dir%/public/images/auteurs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
